package com.estivate;

import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Type;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import javax.naming.directory.AttributeInUseException;
import javax.persistence.AttributeConverter;
import javax.persistence.Convert;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.estivate.entity.CachedEntity;
import com.estivate.query.EstivateAggregator;
import com.estivate.query.EstivateCriterion;
import com.estivate.query.EstivateJoin;
import com.estivate.query.EstivateNode;
import com.estivate.query.EstivateQuery;
import com.estivate.query.EstivateQuery.Entity;
import com.estivate.util.StringPipe;

import lombok.SneakyThrows;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class ConnectionExecutor {
	
	final public Connection connection;
	
	public ConnectionExecutor(Connection connection) {
		this.connection = connection;
	}
	
	@SneakyThrows
	public <U> U uniqueResult(EstivateQuery query, Class<U> clazz) {
		
		
		EstivateStatement statement = EstivateStatement.toStatement(connection, query);
		
		statement.execute();
        
        ResultSet resultSet = statement.getResultSet();
    	ResultSetMetaData metadata = resultSet.getMetaData();
        
        if(resultSet.next()) {

        	Map<String, String> map = new HashMap<>();
        	for(int i = 1; i <= metadata.getColumnCount(); i++) {
        		map.put(metadata.getColumnLabel(i), resultSet.getString(i));
        	}

        	EstivateResult result = new EstivateResult(query, map);
        	U object = result.mapAs(clazz);
        	
        	return object;
        }
        return null;
	}
	
	
	@SneakyThrows
	public List<EstivateResult> list(EstivateQuery joinQuery){
		
		EstivateStatement statement = EstivateStatement.toStatement(connection, joinQuery);
		
        statement.execute();
        
        ResultSet resultSet = statement.getResultSet();
        
        
        List<EstivateResult> results = new ArrayList<>();
        
        while(resultSet.next()) {
        	Map<String, String> map = new HashMap<>();
        	ResultSetMetaData metadata = resultSet.getMetaData();

        	for(int i = 1; i <= metadata.getColumnCount(); i++) {
        		map.put(metadata.getColumnLabel(i), resultSet.getString(i));
        	}
        	EstivateResult result = new EstivateResult(joinQuery, map);
        	results.add(result);
        }
        
        return results;
		
	}
	
	
	public <U> List<U> listAs(EstivateQuery joinQuery, Class<U> clazz) {
		List<EstivateResult> results = list(joinQuery);
		List<U> output = new ArrayList<>();
		for(EstivateResult result : results) {
			output.add(result.mapAs(clazz));
		}
		return output;
	}
	
	@SneakyThrows
	public <U> U saveOrUpdate(U object) {
		
		Field idField = getIdField(object);
		idField.setAccessible(true);
		if(idField != null && idField.getLong(object) == 0L) {
			insert(object);
		}
		else {
			update(object);
		}
		
		if(object instanceof CachedEntity) {
			((CachedEntity) object).saveState();
		}
		
		return object;
	}
	
	@SneakyThrows
	private <U> U insert(U object) {
		

		List<String> fieldValueList = new ArrayList<>();

		EstivateStatement statement = new EstivateStatement(connection)
				.appendQuery("INSERT INTO ")
				.appendQuery(EstivateQuery.nameMapper.mapEntity(object.getClass()));

		
		for(Field field : object.getClass().getDeclaredFields()) {
			field.setAccessible(true);
			// Skip Id, will be auto generated by db
			if(field.isAnnotationPresent(Id.class)) {
				continue;
			}
			
			try {
				
				if(field.get(object) == null) {
					continue;
				}
				
				fieldValueList.add(field.getName());
				statement.appendValue(object.getClass(), field.getName(), field.get(object));
				//EstivateUtil.compileAttribute(entity.getClass(), field.getName(), field.get(entity)));
				
			}
			catch(Exception e) {
				log.error("Cannot map field "+field.getName(), e);
			}
			
		}
				
		statement.appendQuery("(")
				.appendQuery(fieldValueList.stream().collect(Collectors.joining(", ")))
				.appendQuery(") VALUES (")
				.appendQuery(fieldValueList.stream().map(x -> "?").collect(Collectors.joining(", ")))
				.appendQuery(")");
		
		
				
		statement.execute();
		
		ResultSet rs = statement.getGeneratedKeys();
		if (rs.next()) {
			Field field = getIdField(object);
			field.setAccessible(true);
			field.setLong(object, rs.getLong(1));
		}
		else {
			return null;
		}
		
		return object;
	}

	
	@SneakyThrows
	public boolean create(Class entityClass) {
		
		List<String> fields = new ArrayList<>();
		for(Field field : entityClass.getDeclaredFields()) {
			StringPipe fieldCreation = new StringPipe();
			fieldCreation.separator(" ");
			
			fieldCreation.append(field.getName());
			
			Class returnClass = field.getType();
			
			if(field.getDeclaredAnnotation(Convert.class) != null) {
				returnClass = String.class;
			}
			
			if(returnClass.isEnum()) {

				if(field.getDeclaredAnnotation(Enumerated.class) != null && field.getDeclaredAnnotation(Enumerated.class).value() != null && field.getDeclaredAnnotation(Enumerated.class).value() == EnumType.STRING) {
					returnClass = String.class;
				}
				else {
					returnClass = Integer.class;
				}
			}
			
			if(returnClass == Integer.class || returnClass == Long.class || returnClass == Long.TYPE) {
				fieldCreation.append("INT");
			}
			else if(returnClass == String.class) {
				fieldCreation.append("VARCHAR");
			}
			else if(returnClass == Boolean.class || returnClass == boolean.class) {
				fieldCreation.append("BOOL");
			}
			else if(returnClass == java.util.Date.class || returnClass == java.sql.Date.class) {
				fieldCreation.append("DATE");
			}
			else {
				throw new RuntimeException("Cannot map type "+field.getType());
			}
			
			if(field.isAnnotationPresent(Id.class)) {
				fieldCreation.append("PRIMARY KEY");
			}
			
			if(field.getDeclaredAnnotation(GeneratedValue.class) != null) {
				GeneratedValue generatedValue = field.getDeclaredAnnotation(GeneratedValue.class);
				if(generatedValue.strategy() == GenerationType.IDENTITY) {
					fieldCreation.append("AUTO_INCREMENT");
				}
			}
			
			
			fields.add(fieldCreation.toString());
		}
		
		String result = "CREATE TABLE "+entityClass.getSimpleName()+" ("+fields.stream().collect(Collectors.joining(", "))+")";
		
		PreparedStatement statement = connection.prepareStatement(result);
		
		return statement.execute();
		
		
	}
	
	private Field getIdField(Object object) {
		for(Field field : object.getClass().getDeclaredFields()) {
			
			// Skip Id, will be auto generated by db
			if(field.isAnnotationPresent(Id.class)) {
				return field;
			}
		}
		return null;
	}
	
	@SneakyThrows
	public void update(Object entity) {

		List<Field> updatedFields = List.of(entity.getClass().getFields());

		if(entity instanceof CachedEntity) {
			updatedFields = ((CachedEntity) entity).updatedFields();
		}
		
		// No change to entity
		if(updatedFields.isEmpty()) {
			return;
		}
		
		Field idField = EstivateUtil.getFieldWithAnnotation(entity.getClass(), Id.class);
		
		if(idField == null) {
			log.error("No @Id field on class "+entity.getClass());
			return;
		}
		
		idField.setAccessible(true);
		Long id = idField.getLong(entity);
		if(id == null || id == 0) {
			log.error("Null or 0 value id for entity, no update possible");
		}
		
		// 1. Create query
		EstivateStatement statement = new EstivateStatement(connection)
				.appendQuery("UPDATE ")
				.appendQuery(EstivateQuery.nameMapper.mapEntity(entity.getClass()))
				.appendQuery(" SET ");
				
				//String query = "UPDATE "+EstivateQuery.nameMapper.mapEntity(entity.getClass())+" SET ";

		// 2. List updated fields
		statement.appendQuery(updatedFields.stream().map(x-> EstivateQuery.nameMapper.mapEntityAttribute(entity.getClass(), x.getName()) + " = ?").collect(Collectors.joining(", ")));
		
		for(Field field : updatedFields) {
			statement.appendValue(entity.getClass(), field.getName(), field.get(entity));
		}
		
		
		statement.appendQuery(" WHERE "+EstivateQuery.nameMapper.mapAttribute(idField.getName())+" = ?");
		statement.appendValue(entity.getClass(), idField.getName(), idField.getLong(entity));
		
		
		
		boolean check = statement.execute();
		
		System.out.println(check);
		
	}



}
